### ISSUE TITLE
Setting up webhooks

### ISSUE THREAD

**Issue by tomgatzgates** [joluet/MondoAndroid#5]
Hey, 

Are you able to update the docs. Specially about the Webhook url and the GCM url? 

Thanks,
Tom

**Comment by joluet** [comment]
Hi Tom, 

I've just changed the GCM configuration and added the default configuration to the repository.
So, by default the app now uses a small server app that I've hosted on Heroku to convert webhooks from Mondo into GCM push notifications. Please see the updated readme for details.

Cheers,
Jonas
